server:
  port: 7777
  servlet:
    context-path: "/user"

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: Safina@2606
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create
  application:
    name: AUTH-SERVICE
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}

jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
